baseURL = 'https://lionfish-app-bdbno.ondigitalocean.app/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = "Pacific Poker Tour"
theme = "pptcustom"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Events"
  subtitle = "Upcoming events will be listed here"
  mainSections = ["post","posts"]
  logo = "img/ppt-logo-square.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "JH"
  website = "https://webdev.evlis.org/"
  email = "youremail@domain.com"
  github = "https://github.com/EclecticPeddlerAtelier/PacificPokerTour"
  twitter = "username"
  reddit = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  mastodon = "url"
  discord = "invite code (https://discord.gg/XXXXXXX)"

  #facebook = "username"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #strava = "userid"


[[menu.main]]
    name = "Players"
    url = "page/players/"
    weight = 1

[[menu.main]]
    identifier = "events"
    name = "Events"
    weight = 2

[[menu.main]]
    parent = "events"
    name = "Coming Events"
    url = "page/future_events"
    weight = 1

[[menu.main]]
    parent = "events"
    name = "Past Events"
    url = "page/past_events"
    weight = 2

[[menu.main]]
    name = "Leaderboard"
    url = "/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 5